#pragma once

#define WINDOW_WIDTH 620
#define WINDOW_HEIGHT 480

#define LOGICAL_SCREEN_WIDTH (WINDOW_WIDTH/2)
#define LOGICAL_SCREEN_HEIGHT (WINDOW_HEIGHT/2)

#define FPS 60
#define TARGET_FRAME_TIME (1000 / FPS)

#define GRAVITY_FORCE 3.0f
#define JUMP_FORCE 1.5f
#define MAX_VERTICAL_SPEED 2.3f
